[build]
base = "."
publish = "web-garagem/dist"
command = "npm install --prefix web-garagem && npm run build --prefix web-garagem && npm install --prefix api"
functions = "api/netlify/functions"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
